### Site Settings ###
title               : Akshat's Portfolio
description         : >-
                      Passionate Software Engineer, 
                      Pure Math Enthusiast,
                      Lifelong learner
baseurl             : ""                   
repository          : akshatpoddar/akshatpoddar.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Akshat Poddar
  image             : https://i.imgur.com/uyDNQnn.jpg
  email             : akshatpoddar312002@gmail.com
  github            : akshatpoddar
# kaggle            : your_username
  linkedin          : akshat-poddar
# twitter           : your_username




### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: akshat-p                    # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id



### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
